version: 3
tasks:
  install:
    dir: ./
    cmds:
      - poetry lock --no-update
      - poetry install
      - poetry env use python3.12


  format:
    dir: ./
    cmds:
      - poetry run ruff format 
      - poetry run ruff check --fix

  unit:
    dir: ./
    cmds:
      - poetry run pytest src/pysrc/test
