version: 3
tasks:
  install:
    dir: ./
    cmds:
      - poetry lock --no-update
      - poetry install
      - poetry env use python3.12

  test:
    dir: ./
    cmds:
      - task lint
      - task unit


  lint:
    dir: ./
    cmds:
      - poetry run mypy .
      - poetry run ruff check .

  format:
    dir: ./
    cmds:
      - poetry run ruff format 
      - poetry run ruff check --fix

  unit:
    dir: ./
    cmds:
      - poetry run pytest src/pysrc/test
