name: CI - unit-tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install project dependencies
      run: |
        python -m pip install --upgrade pip
        pipx install poetry

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x

    - name: Install poetry dependencies
      run: task install
    
    - name: Runs unit tests
      run: poetry run pytest src/pysrc/test